//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19Radar.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Covid19Radar.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonAgree {
            get {
                return ResourceManager.GetString("ButtonAgree", resourceCulture);
            }
        }
        
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        internal static string SettingsPageButton1 {
            get {
                return ResourceManager.GetString("SettingsPageButton1", resourceCulture);
            }
        }
        
        internal static string TitleLicenseAgreement {
            get {
                return ResourceManager.GetString("TitleLicenseAgreement", resourceCulture);
            }
        }
        
        internal static string UrlPrivacyPolicy {
            get {
                return ResourceManager.GetString("UrlPrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string TitileUserStatusSettings {
            get {
                return ResourceManager.GetString("TitileUserStatusSettings", resourceCulture);
            }
        }
        
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        internal static string DialogNetworkConnectionError {
            get {
                return ResourceManager.GetString("DialogNetworkConnectionError", resourceCulture);
            }
        }
        
        internal static string ButtonNotNow {
            get {
                return ResourceManager.GetString("ButtonNotNow", resourceCulture);
            }
        }
        
        internal static string MainExposures {
            get {
                return ResourceManager.GetString("MainExposures", resourceCulture);
            }
        }
        
        internal static string NotifyOthersLearnMoreUrl {
            get {
                return ResourceManager.GetString("NotifyOthersLearnMoreUrl", resourceCulture);
            }
        }
        
        internal static string MainTutorial {
            get {
                return ResourceManager.GetString("MainTutorial", resourceCulture);
            }
        }
        
        internal static string ExposuresPageNoExposures {
            get {
                return ResourceManager.GetString("ExposuresPageNoExposures", resourceCulture);
            }
        }
        
        internal static string ExposuresPageNoExposuresInfo {
            get {
                return ResourceManager.GetString("ExposuresPageNoExposuresInfo", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDialogExceptionText {
            get {
                return ResourceManager.GetString("NotifyOtherPageDialogExceptionText", resourceCulture);
            }
        }
        
        internal static string ButtonFailed {
            get {
                return ResourceManager.GetString("ButtonFailed", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDialogSubmittedText {
            get {
                return ResourceManager.GetString("NotifyOtherPageDialogSubmittedText", resourceCulture);
            }
        }
        
        internal static string ButtonComplete {
            get {
                return ResourceManager.GetString("ButtonComplete", resourceCulture);
            }
        }
        
        internal static string LoadingTextSubmittingDiagnosis {
            get {
                return ResourceManager.GetString("LoadingTextSubmittingDiagnosis", resourceCulture);
            }
        }
        
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        internal static string LoadingTextDeleting {
            get {
                return ResourceManager.GetString("LoadingTextDeleting", resourceCulture);
            }
        }
        
        internal static string HomePageHeader2Description {
            get {
                return ResourceManager.GetString("HomePageHeader2Description", resourceCulture);
            }
        }
        
        internal static string HomePageHeader3Title {
            get {
                return ResourceManager.GetString("HomePageHeader3Title", resourceCulture);
            }
        }
        
        internal static string HomePageHeader3Description {
            get {
                return ResourceManager.GetString("HomePageHeader3Description", resourceCulture);
            }
        }
        
        internal static string ButtonShare {
            get {
                return ResourceManager.GetString("ButtonShare", resourceCulture);
            }
        }
        
        internal static string ButtonNotifyOtherPage {
            get {
                return ResourceManager.GetString("ButtonNotifyOtherPage", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicyPageTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyPageTitle", resourceCulture);
            }
        }
        
        internal static string LoadingTextRegistering {
            get {
                return ResourceManager.GetString("LoadingTextRegistering", resourceCulture);
            }
        }
        
        internal static string SettingsPageDialogResetText {
            get {
                return ResourceManager.GetString("SettingsPageDialogResetText", resourceCulture);
            }
        }
        
        internal static string SettingsPageDialogResetTitle {
            get {
                return ResourceManager.GetString("SettingsPageDialogResetTitle", resourceCulture);
            }
        }
        
        internal static string SettingsPageDialogResetCompletedText {
            get {
                return ResourceManager.GetString("SettingsPageDialogResetCompletedText", resourceCulture);
            }
        }
        
        internal static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        internal static string SettingsPageLabel1 {
            get {
                return ResourceManager.GetString("SettingsPageLabel1", resourceCulture);
            }
        }
        
        internal static string SettingsPageDescription1 {
            get {
                return ResourceManager.GetString("SettingsPageDescription1", resourceCulture);
            }
        }
        
        internal static string SettingsPageLabel2 {
            get {
                return ResourceManager.GetString("SettingsPageLabel2", resourceCulture);
            }
        }
        
        internal static string SettingsPageDescription2 {
            get {
                return ResourceManager.GetString("SettingsPageDescription2", resourceCulture);
            }
        }
        
        internal static string SettingsPageLabel3 {
            get {
                return ResourceManager.GetString("SettingsPageLabel3", resourceCulture);
            }
        }
        
        internal static string SettingsPageDescription3 {
            get {
                return ResourceManager.GetString("SettingsPageDescription3", resourceCulture);
            }
        }
        
        internal static string ButtonReturnToRegistration {
            get {
                return ResourceManager.GetString("ButtonReturnToRegistration", resourceCulture);
            }
        }
        
        internal static string PositiveRegistrationText {
            get {
                return ResourceManager.GetString("PositiveRegistrationText", resourceCulture);
            }
        }
        
        internal static string PositiveRegistrationConfirmText {
            get {
                return ResourceManager.GetString("PositiveRegistrationConfirmText", resourceCulture);
            }
        }
        
        internal static string HelpMenuPageTitle {
            get {
                return ResourceManager.GetString("HelpMenuPageTitle", resourceCulture);
            }
        }
        
        internal static string HelpMenuPageLabel1 {
            get {
                return ResourceManager.GetString("HelpMenuPageLabel1", resourceCulture);
            }
        }
        
        internal static string HelpMenuPageLabel2 {
            get {
                return ResourceManager.GetString("HelpMenuPageLabel2", resourceCulture);
            }
        }
        
        internal static string HelpMenuPageLabel3 {
            get {
                return ResourceManager.GetString("HelpMenuPageLabel3", resourceCulture);
            }
        }
        
        internal static string HelpMenuPageLabel4 {
            get {
                return ResourceManager.GetString("HelpMenuPageLabel4", resourceCulture);
            }
        }
        
        internal static string HelpPage1Title {
            get {
                return ResourceManager.GetString("HelpPage1Title", resourceCulture);
            }
        }
        
        internal static string HelpPage2Title {
            get {
                return ResourceManager.GetString("HelpPage2Title", resourceCulture);
            }
        }
        
        internal static string HelpPage3Title {
            get {
                return ResourceManager.GetString("HelpPage3Title", resourceCulture);
            }
        }
        
        internal static string HelpPage4Title {
            get {
                return ResourceManager.GetString("HelpPage4Title", resourceCulture);
            }
        }
        
        internal static string HelpPage1Description1Text {
            get {
                return ResourceManager.GetString("HelpPage1Description1Text", resourceCulture);
            }
        }
        
        internal static string HelpPage1Description2Title {
            get {
                return ResourceManager.GetString("HelpPage1Description2Title", resourceCulture);
            }
        }
        
        internal static string HelpPage1Description2Text {
            get {
                return ResourceManager.GetString("HelpPage1Description2Text", resourceCulture);
            }
        }
        
        internal static string HelpPage1Description3Title {
            get {
                return ResourceManager.GetString("HelpPage1Description3Title", resourceCulture);
            }
        }
        
        internal static string HelpPage1Description3Text {
            get {
                return ResourceManager.GetString("HelpPage1Description3Text", resourceCulture);
            }
        }
        
        internal static string HelpPage2Description1 {
            get {
                return ResourceManager.GetString("HelpPage2Description1", resourceCulture);
            }
        }
        
        internal static string HelpPage2Description2 {
            get {
                return ResourceManager.GetString("HelpPage2Description2", resourceCulture);
            }
        }
        
        internal static string HelpPage2Description3 {
            get {
                return ResourceManager.GetString("HelpPage2Description3", resourceCulture);
            }
        }
        
        internal static string HelpPage2Label1 {
            get {
                return ResourceManager.GetString("HelpPage2Label1", resourceCulture);
            }
        }
        
        internal static string HelpPage2Label2 {
            get {
                return ResourceManager.GetString("HelpPage2Label2", resourceCulture);
            }
        }
        
        internal static string HelpPage2Label3 {
            get {
                return ResourceManager.GetString("HelpPage2Label3", resourceCulture);
            }
        }
        
        internal static string HelpPage4ButtonText {
            get {
                return ResourceManager.GetString("HelpPage4ButtonText", resourceCulture);
            }
        }
        
        internal static string HelpPage4Description {
            get {
                return ResourceManager.GetString("HelpPage4Description", resourceCulture);
            }
        }
        
        internal static string HelpPage3Description1 {
            get {
                return ResourceManager.GetString("HelpPage3Description1", resourceCulture);
            }
        }
        
        internal static string HelpPage3Description2 {
            get {
                return ResourceManager.GetString("HelpPage3Description2", resourceCulture);
            }
        }
        
        internal static string HelpPage3Description3 {
            get {
                return ResourceManager.GetString("HelpPage3Description3", resourceCulture);
            }
        }
        
        internal static string HelpPage3Description4 {
            get {
                return ResourceManager.GetString("HelpPage3Description4", resourceCulture);
            }
        }
        
        internal static string HelpPage3Description5 {
            get {
                return ResourceManager.GetString("HelpPage3Description5", resourceCulture);
            }
        }
        
        internal static string HelpPage3Description6 {
            get {
                return ResourceManager.GetString("HelpPage3Description6", resourceCulture);
            }
        }
        
        internal static string NotContactPageTitle {
            get {
                return ResourceManager.GetString("NotContactPageTitle", resourceCulture);
            }
        }
        
        internal static string NotContactPageLabel1 {
            get {
                return ResourceManager.GetString("NotContactPageLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From app settings, you can stop using the app and delete user data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage4Description {
            get {
                return ResourceManager.GetString("NotContactPageDescription1", resourceCulture);
            }
        }
        
        internal static string NotContactPageButtonText {
            get {
                return ResourceManager.GetString("NotContactPageButtonText", resourceCulture);
            }
        }
        
        internal static string ThankYouNotifyOtherPageLabel1 {
            get {
                return ResourceManager.GetString("ThankYouNotifyOtherPageLabel1", resourceCulture);
            }
        }
        
        internal static string ThankYouNotifyOtherPageDescription1 {
            get {
                return ResourceManager.GetString("ThankYouNotifyOtherPageDescription1", resourceCulture);
            }
        }
        
        internal static string TutorialPage3Title {
            get {
                return ResourceManager.GetString("TutorialPage3Title", resourceCulture);
            }
        }
        
        internal static string TutorialPage3ButtonText {
            get {
                return ResourceManager.GetString("TutorialPage3ButtonText", resourceCulture);
            }
        }
        
        internal static string TutorialPage6Label1 {
            get {
                return ResourceManager.GetString("TutorialPage6Label1", resourceCulture);
            }
        }
        
        internal static string TutorialPage6ButtonText1 {
            get {
                return ResourceManager.GetString("TutorialPage6ButtonText1", resourceCulture);
            }
        }
        
        internal static string TutorialPage6ButtonText2 {
            get {
                return ResourceManager.GetString("TutorialPage6ButtonText2", resourceCulture);
            }
        }
        
        internal static string HelpPage1MainTitle {
            get {
                return ResourceManager.GetString("HelpPage1MainTitle", resourceCulture);
            }
        }
        
        internal static string ContactedNotifyPageButton1 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageButton1", resourceCulture);
            }
        }
        
        internal static string ContactedNotifyPageButton2 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageButton2", resourceCulture);
            }
        }
        
        internal static string ContactedNotifyPageButton3 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageButton3", resourceCulture);
            }
        }
        
        internal static string ContactedNotifyPageCountText {
            get {
                return ResourceManager.GetString("ContactedNotifyPageCountText", resourceCulture);
            }
        }
        
        internal static string ContactedNotifyPageDescription1 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageDescription1", resourceCulture);
            }
        }
        
        internal static string ContactedNotifyPageDescription2 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageDescription2", resourceCulture);
            }
        }
        
        internal static string ContactedNotifyPageMainText {
            get {
                return ResourceManager.GetString("ContactedNotifyPageMainText", resourceCulture);
            }
        }
        
        internal static string ContactedNotifyPageTitle {
            get {
                return ResourceManager.GetString("ContactedNotifyPageTitle", resourceCulture);
            }
        }
        
        internal static string InqueryPageDescription1 {
            get {
                return ResourceManager.GetString("InqueryPageDescription1", resourceCulture);
            }
        }
        
        internal static string InqueryPageDescription2 {
            get {
                return ResourceManager.GetString("InqueryPageDescription2", resourceCulture);
            }
        }
        
        internal static string InqueryPageTitle {
            get {
                return ResourceManager.GetString("InqueryPageTitle", resourceCulture);
            }
        }
        
        internal static string HomePageDescription1 {
            get {
                return ResourceManager.GetString("HomePageDescription1", resourceCulture);
            }
        }
        
        internal static string HomePageDescription2 {
            get {
                return ResourceManager.GetString("HomePageDescription2", resourceCulture);
            }
        }
        
        internal static string HomePageDescription3 {
            get {
                return ResourceManager.GetString("HomePageDescription3", resourceCulture);
            }
        }
        
        internal static string HomePageDescription4 {
            get {
                return ResourceManager.GetString("HomePageDescription4", resourceCulture);
            }
        }
        
        internal static string HomePageDescription5 {
            get {
                return ResourceManager.GetString("HomePageDescription5", resourceCulture);
            }
        }
        
        internal static string HomePageDescription6 {
            get {
                return ResourceManager.GetString("HomePageDescription6", resourceCulture);
            }
        }
        
        internal static string HomePageDescription7 {
            get {
                return ResourceManager.GetString("HomePageDescription7", resourceCulture);
            }
        }
        
        internal static string HomePageTitle1 {
            get {
                return ResourceManager.GetString("HomePageTitle1", resourceCulture);
            }
        }
        
        internal static string TermsofservicePageTitle {
            get {
                return ResourceManager.GetString("TermsofservicePageTitle", resourceCulture);
            }
        }
        
        internal static string TutorialPage2Description1 {
            get {
                return ResourceManager.GetString("TutorialPage2Description1", resourceCulture);
            }
        }
        
        internal static string TutorialPage2Description2 {
            get {
                return ResourceManager.GetString("TutorialPage2Description2", resourceCulture);
            }
        }
        
        internal static string TutorialPage2Description3 {
            get {
                return ResourceManager.GetString("TutorialPage2Description3", resourceCulture);
            }
        }
        
        internal static string TutorialPage2Description4 {
            get {
                return ResourceManager.GetString("TutorialPage2Description4", resourceCulture);
            }
        }
        
        internal static string TutorialPage2Description5 {
            get {
                return ResourceManager.GetString("TutorialPage2Description5", resourceCulture);
            }
        }
        
        internal static string TutorialPage2Title {
            get {
                return ResourceManager.GetString("TutorialPage2Title", resourceCulture);
            }
        }
        
        internal static string TutorialPage5Description1 {
            get {
                return ResourceManager.GetString("TutorialPage5Description1", resourceCulture);
            }
        }
        
        internal static string TutorialPage5Description2 {
            get {
                return ResourceManager.GetString("TutorialPage5Description2", resourceCulture);
            }
        }
        
        internal static string TutorialPage5Description3 {
            get {
                return ResourceManager.GetString("TutorialPage5Description3", resourceCulture);
            }
        }
        
        internal static string TutorialPage5Description4 {
            get {
                return ResourceManager.GetString("TutorialPage5Description4", resourceCulture);
            }
        }
        
        internal static string TutorialPage5Title {
            get {
                return ResourceManager.GetString("TutorialPage5Title", resourceCulture);
            }
        }
        
        internal static string MenuPageTitle {
            get {
                return ResourceManager.GetString("MenuPageTitle", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageButton {
            get {
                return ResourceManager.GetString("NotifyOtherPageButton", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDescription1 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription1", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDescription2 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription2", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageLabel {
            get {
                return ResourceManager.GetString("NotifyOtherPageLabel", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageTitle {
            get {
                return ResourceManager.GetString("NotifyOtherPageTitle", resourceCulture);
            }
        }
        
        internal static string TutorialPage1Button {
            get {
                return ResourceManager.GetString("TutorialPage1Button", resourceCulture);
            }
        }
        
        internal static string TutorialPage1Description1 {
            get {
                return ResourceManager.GetString("TutorialPage1Description1", resourceCulture);
            }
        }
        
        internal static string TutorialPage1Description2 {
            get {
                return ResourceManager.GetString("TutorialPage1Description2", resourceCulture);
            }
        }
        
        internal static string TutorialPage1Description3 {
            get {
                return ResourceManager.GetString("TutorialPage1Description3", resourceCulture);
            }
        }
        
        internal static string TutorialPage1Title1 {
            get {
                return ResourceManager.GetString("TutorialPage1Title1", resourceCulture);
            }
        }
        
        internal static string TutorialPage1Title2 {
            get {
                return ResourceManager.GetString("TutorialPage1Title2", resourceCulture);
            }
        }
        
        internal static string TutorialPage4Button1 {
            get {
                return ResourceManager.GetString("TutorialPage4Button1", resourceCulture);
            }
        }
        
        internal static string TutorialPage4Button2 {
            get {
                return ResourceManager.GetString("TutorialPage4Button2", resourceCulture);
            }
        }
        
        internal static string TutorialPage4Description {
            get {
                return ResourceManager.GetString("TutorialPage4Description", resourceCulture);
            }
        }
        
        internal static string TutorialPage4Label {
            get {
                return ResourceManager.GetString("TutorialPage4Label", resourceCulture);
            }
        }
        
        internal static string TutorialPage4Title1 {
            get {
                return ResourceManager.GetString("TutorialPage4Title1", resourceCulture);
            }
        }
        
        internal static string TutorialPage4Title2 {
            get {
                return ResourceManager.GetString("TutorialPage4Title2", resourceCulture);
            }
        }
        
        internal static string HomePageDescription0 {
            get {
                return ResourceManager.GetString("HomePageDescription0", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageLabel2 {
            get {
                return ResourceManager.GetString("NotifyOtherPageLabel2", resourceCulture);
            }
        }
        
        internal static string SubmitConsentPageDescription1 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription1", resourceCulture);
            }
        }
        
        internal static string SubmitConsentPageDescription2 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription2", resourceCulture);
            }
        }
        
        internal static string SubmitConsentPageDescription3 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription3", resourceCulture);
            }
        }
        
        internal static string SubmitConsentPageDescription4 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription4", resourceCulture);
            }
        }
        
        internal static string SubmitConsentPageDescription5 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription5", resourceCulture);
            }
        }
        
        internal static string SubmitConsentPageDescription6 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription6", resourceCulture);
            }
        }
        
        internal static string SubmitConsentPageTitle1 {
            get {
                return ResourceManager.GetString("SubmitConsentPageTitle1", resourceCulture);
            }
        }
        
        internal static string SubmitConsentPageTitle2 {
            get {
                return ResourceManager.GetString("SubmitConsentPageTitle2", resourceCulture);
            }
        }
        
        internal static string ExposureNotificationServiceMessage4 {
            get {
                return ResourceManager.GetString("ExposureNotificationServiceMessage4", resourceCulture);
            }
        }
        
        internal static string ExposuresPageTitle {
            get {
                return ResourceManager.GetString("ExposuresPageTitle", resourceCulture);
            }
        }
        
        internal static string ExposuresPageLabel1 {
            get {
                return ResourceManager.GetString("ExposuresPageLabel1", resourceCulture);
            }
        }
        
        internal static string UrlTermOfUse {
            get {
                return ResourceManager.GetString("UrlTermOfUse", resourceCulture);
            }
        }
        
        internal static string UrlContactedForm {
            get {
                return ResourceManager.GetString("UrlContactedForm", resourceCulture);
            }
        }
        
        internal static string UrlContactedPhone {
            get {
                return ResourceManager.GetString("UrlContactedPhone", resourceCulture);
            }
        }
        
        internal static string LocalNotificationDescription {
            get {
                return ResourceManager.GetString("LocalNotificationDescription", resourceCulture);
            }
        }
        
        internal static string LocalNotificationTitle {
            get {
                return ResourceManager.GetString("LocalNotificationTitle", resourceCulture);
            }
        }
        
        internal static string LocalNotificationPermittedDescription {
            get {
                return ResourceManager.GetString("LocalNotificationPermittedDescription", resourceCulture);
            }
        }
        
        internal static string LocalNotificationPermittedTitle {
            get {
                return ResourceManager.GetString("LocalNotificationPermittedTitle", resourceCulture);
            }
        }
        
        internal static string InqueryPageDescription3 {
            get {
                return ResourceManager.GetString("InqueryPageDescription3", resourceCulture);
            }
        }
        
        internal static string InqueryPageDescription4 {
            get {
                return ResourceManager.GetString("InqueryPageDescription4", resourceCulture);
            }
        }
        
        internal static string InqueryMailBody {
            get {
                return ResourceManager.GetString("InqueryMailBody", resourceCulture);
            }
        }
        
        internal static string InqueryMailSubject {
            get {
                return ResourceManager.GetString("InqueryMailSubject", resourceCulture);
            }
        }
        
        internal static string HomePagePastDays {
            get {
                return ResourceManager.GetString("HomePagePastDays", resourceCulture);
            }
        }
        
        internal static string ExposureNotificationStatusMessageActive {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageActive", resourceCulture);
            }
        }
        
        internal static string ExposureNotificationStatusMessageBluetoothOff {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageBluetoothOff", resourceCulture);
            }
        }
        
        internal static string ExposureNotificationStatusMessageDisabled {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageDisabled", resourceCulture);
            }
        }
        
        internal static string ExposureNotificationStatusMessageIsOptined {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageIsOptined", resourceCulture);
            }
        }
        
        internal static string ExposureNotificationStatusMessageRestricted {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageRestricted", resourceCulture);
            }
        }
        
        internal static string ExposureNotificationStatusMessageUnknown {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageUnknown", resourceCulture);
            }
        }
        
        internal static string DialogNetworkConnectionErrorTitle {
            get {
                return ResourceManager.GetString("DialogNetworkConnectionErrorTitle", resourceCulture);
            }
        }
        
        internal static string DialogExposureNotificationStartupErrorTitle {
            get {
                return ResourceManager.GetString("DialogExposureNotificationStartupErrorTitle", resourceCulture);
            }
        }
        
        internal static string DialogExposureNotificationStartupError {
            get {
                return ResourceManager.GetString("DialogExposureNotificationStartupError", resourceCulture);
            }
        }
        
        internal static string ExposureNotificationHandler1ErrorMessage {
            get {
                return ResourceManager.GetString("ExposureNotificationHandler1ErrorMessage", resourceCulture);
            }
        }
        
        internal static string ExposureNotificationHandler2ErrorMessage {
            get {
                return ResourceManager.GetString("ExposureNotificationHandler2ErrorMessage", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDiag1Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag1Message", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDiag1Title {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag1Title", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDiag2Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag2Message", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDiag3Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag3Message", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDiag3Title {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag3Title", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDiag4Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag4Message", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDiag5Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag5Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://covid19radarjpnprod.z11.web.core.windows.net/phone.json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlContactedPhone {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag6Message", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDiag6Title {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag6Title", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDiagAppClose {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiagAppClose", resourceCulture);
            }
        }
        
        internal static string NotifyOtherPageDiagErrorTitle {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiagErrorTitle", resourceCulture);
            }
        }
    }
}
