//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19Radar.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covid19Radar.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   新型コロナウイルス接触確認アプリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいバージョンのアプリが利用可能です。最新バージョンにアップデートしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppUtilsGetNewVersionDescription {
            get {
                return ResourceManager.GetString("AppUtilsGetNewVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新バージョンに更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppUtilsGetNewVersionTitle {
            get {
                return ResourceManager.GetString("AppUtilsGetNewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同意する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonAgree {
            get {
                return ResourceManager.GetString("ButtonAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonComplete {
            get {
                return ResourceManager.GetString("ButtonComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonFailed {
            get {
                return ResourceManager.GetString("ButtonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性情報の登録と他者への匿名通知へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonNotifyOtherPage {
            get {
                return ResourceManager.GetString("ButtonNotifyOtherPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あとで設定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonNotNow {
            get {
                return ResourceManager.GetString("ButtonNotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用中止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録に戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonReturnToRegistration {
            get {
                return ResourceManager.GetString("ButtonReturnToRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   共有する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonShare {
            get {
                return ResourceManager.GetString("ButtonShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性者との接触一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactedNotifyPageButton1 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査等の相談先を探す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactedNotifyPageButton2 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactedNotifyPageCountText {
            get {
                return ResourceManager.GetString("ContactedNotifyPageCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ・発熱等の症状や基礎疾患がある、新型コロナウイルス感染症の陽性者と接触した心当たりがあるなど、検査等の相談を希望される場合は、アプリの案内に従って相談先をご確認ください。
        ///・受診の際に必要となる場合があるため、以下より陽性者との接触一覧のスクリーンショットを保存してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactedNotifyPageDescription1 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性者との接触確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactedNotifyPageMainText {
            get {
                return ResourceManager.GetString("ContactedNotifyPageMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過去14日間の接触 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactedNotifyPageTitle {
            get {
                return ResourceManager.GetString("ContactedNotifyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://corona.go.jp/dashboard/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CoronaGoJPUrl {
            get {
                return ResourceManager.GetString("CoronaGoJPUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposure Notificationを起動できませんでした。端末の設定を開いて、Exposure NotificationをONにするとともに、BluetoothをONにしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogExposureNotificationStartupError {
            get {
                return ResourceManager.GetString("DialogExposureNotificationStartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposure Notification起動エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogExposureNotificationStartupErrorTitle {
            get {
                return ResourceManager.GetString("DialogExposureNotificationStartupErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電波状況の良い場所でもう一度お試しください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogNetworkConnectionError {
            get {
                return ResourceManager.GetString("DialogNetworkConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogNetworkConnectionErrorTitle {
            get {
                return ResourceManager.GetString("DialogNetworkConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposureCountUnit {
            get {
                return ResourceManager.GetString("ExposureCountUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリで入力された処理番号が違います に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposureNotificationHandler1ErrorMessage {
            get {
                return ResourceManager.GetString("ExposureNotificationHandler1ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センターに接続できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposureNotificationHandler2ErrorMessage {
            get {
                return ResourceManager.GetString("ExposureNotificationHandler2ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触記録データに問題があります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposureNotificationHandler3ErrorMessage {
            get {
                return ResourceManager.GetString("ExposureNotificationHandler3ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BluetoothがOffになっています。Bluetoothを有効にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposureNotificationServiceMessage4 {
            get {
                return ResourceManager.GetString("ExposureNotificationServiceMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification機能は許諾の状態です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposureNotificationStatusMessageActive {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BluetoothがOffになっています。Bluetoothを有効にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposureNotificationStatusMessageBluetoothOff {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageBluetoothOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposure Notification機能は無効の状態です。端末の設定を開いて、Exposure NotificationをONにしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposureNotificationStatusMessageDisabled {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用規約に同意する必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposureNotificationStatusMessageIsOptined {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageIsOptined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COVID-19接触通知機能が承認されていません。各OSから承認するか、またはアプリの再インストール後に、再承認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposureNotificationStatusMessageRestricted {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposure Notification機能は非対応の状態です。OSを最新版にアップデートしてください。それでも改善しなければ、appsupport@yourhealthcaredivmailaddress.orgまでお問い合わせください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposureNotificationStatusMessageUnknown {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下の日に陽性者との接触が確認されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposuresPageLabel1 {
            get {
                return ResourceManager.GetString("ExposuresPageLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既知の接触はありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposuresPageNoExposures {
            get {
                return ResourceManager.GetString("ExposuresPageNoExposures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COVID-19陽性を報告した人と接触していた場合は、通知されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposuresPageNoExposuresInfo {
            get {
                return ResourceManager.GetString("ExposuresPageNoExposuresInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過去14日間の接触一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposuresPageTitle {
            get {
                return ResourceManager.GetString("ExposuresPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作情報の取得に失敗しました。もう一度やり直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedMessageToGetOperatingInformation {
            get {
                return ResourceManager.GetString("FailedMessageToGetOperatingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作情報の確認用ファイルの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedMessageToSaveOperatingInformation {
            get {
                return ResourceManager.GetString("FailedMessageToSaveOperatingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作情報の送信に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedMessageToSendOperatingInformation {
            get {
                return ResourceManager.GetString("FailedMessageToSendOperatingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.google.co.jp/search?hl=ja&amp;q=2019年新型コロナウイルス感染症 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GoogleSearchUrl {
            get {
                return ResourceManager.GetString("GoogleSearchUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   どのようにして接触を記録していますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpMenuPageLabel1 {
            get {
                return ResourceManager.GetString("HelpMenuPageLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触の有無はどのように知ることができますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpMenuPageLabel2 {
            get {
                return ResourceManager.GetString("HelpMenuPageLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新型コロナウイルスに感染していると判定されたら に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpMenuPageLabel3 {
            get {
                return ResourceManager.GetString("HelpMenuPageLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触の記録を停止／情報を削除するには に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpMenuPageLabel4 {
            get {
                return ResourceManager.GetString("HelpMenuPageLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使い方 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpMenuPageTitle {
            get {
                return ResourceManager.GetString("HelpMenuPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリを実行した際に、各スマートフォンで接触符号を生成して持ちます。氏名・電話番号などの個人情報やGPSなどスマートフォンの位置情報を使うことはなく、記録されることもありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage1Description1Text {
            get {
                return ResourceManager.GetString("HelpPage1Description1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1メートル以内、15分以上の他のアプリユーザーとの接触は「接触」として記録されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage1Description2Text {
            get {
                return ResourceManager.GetString("HelpPage1Description2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   記録される接触の条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage1Description2Title {
            get {
                return ResourceManager.GetString("HelpPage1Description2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このとき、接触した相手の接触符号の記録をアプリに行います。どちらかの利用者が陽性の登録を行うまでは接触の情報は利用されません。接触の履歴は14日後に消去されます。 ※接触符号は定期的に変わります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage1Description3Text {
            get {
                return ResourceManager.GetString("HelpPage1Description3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触情報の記録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage1Description3Title {
            get {
                return ResourceManager.GetString("HelpPage1Description3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   端末の識別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage1MainTitle {
            get {
                return ResourceManager.GetString("HelpPage1MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触の記録方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage1Title {
            get {
                return ResourceManager.GetString("HelpPage1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触した人の中に新型コロナウイルスの陽性登録された人がいた場合、スマートフォンにプッシュ通知が届きます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage2Description1 {
            get {
                return ResourceManager.GetString("HelpPage2Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最近の接触件数の確認へはホーム画面からも移動することができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage2Description2 {
            get {
                return ResourceManager.GetString("HelpPage2Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触があった日付の一覧を確認できます。また適切な連絡先をお知らせします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage2Description3 {
            get {
                return ResourceManager.GetString("HelpPage2Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage2Label1 {
            get {
                return ResourceManager.GetString("HelpPage2Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage2Label2 {
            get {
                return ResourceManager.GetString("HelpPage2Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性者との接触があった場合 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage2Label3 {
            get {
                return ResourceManager.GetString("HelpPage2Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触の確認方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage2Title {
            get {
                return ResourceManager.GetString("HelpPage2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査により新型コロナウイルスの感染が確認された場合。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage3Description1 {
            get {
                return ResourceManager.GetString("HelpPage3Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保健所等公的機関から登録用の「処理番号」が発行されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage3Description2 {
            get {
                return ResourceManager.GetString("HelpPage3Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本アプリを用いて処理番号の登録を行います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage3Description3 {
            get {
                return ResourceManager.GetString("HelpPage3Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発症日または検査日の２日前以降にあなたと接触した人に通知が届きます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage3Description4 {
            get {
                return ResourceManager.GetString("HelpPage3Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知される情報はランダムな符号のみです。それ以外の、氏名など個人情報や位置情報が送られることはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage3Description5 {
            get {
                return ResourceManager.GetString("HelpPage3Description5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性情報を登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage3Description6 {
            get {
                return ResourceManager.GetString("HelpPage3Description6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   感染していると判定されたら に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage3Title {
            get {
                return ResourceManager.GetString("HelpPage3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリの設定へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage4ButtonText {
            get {
                return ResourceManager.GetString("HelpPage4ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリの設定から、アプリの使用中止と利用者情報の削除を行うことができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage4Description {
            get {
                return ResourceManager.GetString("HelpPage4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   記録の停止／削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPage4Title {
            get {
                return ResourceManager.GetString("HelpPage4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   から に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageDescription0 {
            get {
                return ResourceManager.GetString("HomePageDescription0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageDescription1 {
            get {
                return ResourceManager.GetString("HomePageDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性者との接触を確認する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageDescription2 {
            get {
                return ResourceManager.GetString("HomePageDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新型コロナウイルス陽性と診断されたら に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageDescription3 {
            get {
                return ResourceManager.GetString("HomePageDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性情報の登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageDescription4 {
            get {
                return ResourceManager.GetString("HomePageDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリを周りの人に知らせる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageDescription5 {
            get {
                return ResourceManager.GetString("HomePageDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触通知は全て有効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageDescription6 {
            get {
                return ResourceManager.GetString("HomePageDescription6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触通知が無効になっています。設定ページで接触通知をオンにしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageDescription7 {
            get {
                return ResourceManager.GetString("HomePageDescription7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   周りの人達を守るために匿名での陽性登録へのご協力をお願いいたします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageHeader2Description {
            get {
                return ResourceManager.GetString("HomePageHeader2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本アプリは多くの方にお使いいただくほど効果を発揮します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageHeader3Description {
            get {
                return ResourceManager.GetString("HomePageHeader3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本アプリを広めましょう に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageHeader3Title {
            get {
                return ResourceManager.GetString("HomePageHeader3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePagePastDays {
            get {
                return ResourceManager.GetString("HomePagePastDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageTitle1 {
            get {
                return ResourceManager.GetString("HomePageTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   よくある質問 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InqueryPageButton1 {
            get {
                return ResourceManager.GetString("InqueryPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールでお問い合わせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InqueryPageButton2 {
            get {
                return ResourceManager.GetString("InqueryPageButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作情報を送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InqueryPageButton3 {
            get {
                return ResourceManager.GetString("InqueryPageButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリの改善にご協力ください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InqueryPageDescription1 {
            get {
                return ResourceManager.GetString("InqueryPageDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お問い合わせ後、動作情報を送信していただくことにより、COCOAの改善に役立ちます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InqueryPageDescription2 {
            get {
                return ResourceManager.GetString("InqueryPageDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触確認アプリに関する情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InqueryPageDescription3 {
            get {
                return ResourceManager.GetString("InqueryPageDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリに関するお問い合わせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InqueryPageTitle {
            get {
                return ResourceManager.GetString("InqueryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お問い合わせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InqueryPageTitle_Menu {
            get {
                return ResourceManager.GetString("InqueryPageTitle_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お問い合わせ本文：​\r\n\r\n\r\n\r\n※氏名、電話番号などの個人情報を記入する必要はありません。\r\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InquiryMailBody {
            get {
                return ResourceManager.GetString("InquiryMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触確認アプリに関するお問い合わせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InquiryMailSubject {
            get {
                return ResourceManager.GetString("InquiryMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingTextDeleting {
            get {
                return ResourceManager.GetString("LoadingTextDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingTextRegistering {
            get {
                return ResourceManager.GetString("LoadingTextRegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   診断を提出します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingTextSubmittingDiagnosis {
            get {
                return ResourceManager.GetString("LoadingTextSubmittingDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新型コロナウイルス陽性登録者と接触した可能性があります。詳細はこちら に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LocalNotificationDescription {
            get {
                return ResourceManager.GetString("LocalNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知を無効にしたい場合は、アプリの設定から変更できます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LocalNotificationPermittedDescription {
            get {
                return ResourceManager.GetString("LocalNotificationPermittedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知を有効にしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LocalNotificationPermittedTitle {
            get {
                return ResourceManager.GetString("LocalNotificationPermittedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新型コロナウイルス陽性登録者との接触の可能性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LocalNotificationTitle {
            get {
                return ResourceManager.GetString("LocalNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDataView_FilePath {
            get {
                return ResourceManager.GetString("LogDataView_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDataView_LineNumber {
            get {
                return ResourceManager.GetString("LogDataView_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDataView_LogLevel {
            get {
                return ResourceManager.GetString("LogDataView_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDataView_LogLevel_Debug {
            get {
                return ResourceManager.GetString("LogDataView_LogLevel_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDataView_LogLevel_Error {
            get {
                return ResourceManager.GetString("LogDataView_LogLevel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDataView_LogLevel_Info {
            get {
                return ResourceManager.GetString("LogDataView_LogLevel_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (無効) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDataView_LogLevel_Invalid {
            get {
                return ResourceManager.GetString("LogDataView_LogLevel_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDataView_LogLevel_Verbose {
            get {
                return ResourceManager.GetString("LogDataView_LogLevel_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDataView_LogLevel_Warning {
            get {
                return ResourceManager.GetString("LogDataView_LogLevel_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDataView_Method {
            get {
                return ResourceManager.GetString("LogDataView_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDataView_OutputDate {
            get {
                return ResourceManager.GetString("LogDataView_OutputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogDataView_OutputDate_Unknown {
            get {
                return ResourceManager.GetString("LogDataView_OutputDate_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込み中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogsPage_Loading {
            get {
                return ResourceManager.GetString("LogsPage_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログファイルを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogsPage_Picker {
            get {
                return ResourceManager.GetString("LogsPage_Picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なファイル「{0}」 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogsPage_UnknownFile {
            get {
                return ResourceManager.GetString("LogsPage_UnknownFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogsPageTitle {
            get {
                return ResourceManager.GetString("LogsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainExposures {
            get {
                return ResourceManager.GetString("MainExposures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使い方 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainTutorial {
            get {
                return ResourceManager.GetString("MainTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メニュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPageTitle {
            get {
                return ResourceManager.GetString("MenuPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内閣官房のデータ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewsPageButton_ShowCoronaGoJP {
            get {
                return ResourceManager.GetString("NewsPageButton_ShowCoronaGoJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新情報をGoogleで検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewsPageButton_ShowGoogle {
            get {
                return ResourceManager.GetString("NewsPageButton_ShowGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対策ダッシュボード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewsPageButton_ShowStopCOVID19JP {
            get {
                return ResourceManager.GetString("NewsPageButton_ShowStopCOVID19JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィキペディアの情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewsPageButton_ShowWikipedia {
            get {
                return ResourceManager.GetString("NewsPageButton_ShowWikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンク集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewsPageLabel_Links {
            get {
                return ResourceManager.GetString("NewsPageLabel_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新型コロナに関する情報を調べる事ができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewsPageLabel_LinksDescription {
            get {
                return ResourceManager.GetString("NewsPageLabel_LinksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新情報ページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewsPageTitle {
            get {
                return ResourceManager.GetString("NewsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリを周りの人に知らせる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotContactPageButtonText {
            get {
                return ResourceManager.GetString("NotContactPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引き続き「新しい生活様式」の実践をよろしくお願いいたします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotContactPageDescription1 {
            get {
                return ResourceManager.GetString("NotContactPageDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性者との接触は確認されませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotContactPageLabel1 {
            get {
                return ResourceManager.GetString("NotContactPageLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過去14日間の接触 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotContactPageTitle {
            get {
                return ResourceManager.GetString("NotContactPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageButton {
            get {
                return ResourceManager.GetString("NotifyOtherPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次のような症状がありますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDescription1 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発熱、咳、呼吸困難、全身倦怠感、咽頭痛、鼻汁・鼻閉、頭痛、関節・筋肉痛、下痢、嘔気・嘔吐など に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDescription2 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SMSまたはメールで届いた処理番号を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDescription3 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録すると に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDescription4 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   症状が始まった日または検査を受けた日の2日前以降にあなたと接触した人に通知が行きます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDescription5 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※登録は匿名で行われ、氏名や連絡先など個人が特定される情報が他の人に知られることはありません
        ///※接触した場所がどこなのか記録されたり、他の人に知られることもありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDescription6 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性情報を登録しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDiag1Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag1Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDiag1Title {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセルしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDiag2Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag2Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録開始までしばらくそのままでお待ちください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDiag3Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag3Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録待ち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDiag3Title {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理番号が入力されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDiag4Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag4Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理番号のフォーマットが一致していません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDiag5Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag5Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性記録の登録を行う為にCOVID-19接触のログ記録を有効にする必要があります、アプリかOSの設定から有効にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDiag6Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag6Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COVID-19接触のログ記録を有効にしてください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDiag6Title {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録回数上限になりました。アプリケーションを終了します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDiagAppClose {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiagAppClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDiagErrorTitle {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiagErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   提出に該当する接触記録が確認できませんでした。提出の必要はありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDialogExceptionTargetDiagKeyNotFound {
            get {
                return ResourceManager.GetString("NotifyOtherPageDialogExceptionTargetDiagKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当接触なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDialogExceptionTargetDiagKeyNotFoundTitle {
            get {
                return ResourceManager.GetString("NotifyOtherPageDialogExceptionTargetDiagKeyNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   後でもう一度試してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDialogExceptionText {
            get {
                return ResourceManager.GetString("NotifyOtherPageDialogExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   診断結果の提出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDialogSubmittedText {
            get {
                return ResourceManager.GetString("NotifyOtherPageDialogSubmittedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理番号の取得方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageLabel {
            get {
                return ResourceManager.GetString("NotifyOtherPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8桁の処理番号を入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageLabel2 {
            get {
                return ResourceManager.GetString("NotifyOtherPageLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   直近の新型コロナウイルス感染症の検査を受けた日を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageNoSymptomsDescription1 {
            get {
                return ResourceManager.GetString("NotifyOtherPageNoSymptomsDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageRadioButtonNo {
            get {
                return ResourceManager.GetString("NotifyOtherPageRadioButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ある に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageRadioButtonYes {
            get {
                return ResourceManager.GetString("NotifyOtherPageRadioButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性情報の登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageTitle {
            get {
                return ResourceManager.GetString("NotifyOtherPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   症状が始まった最初の日を入力してください。（覚えている範囲で一番古い日付を入力してください。入力した日付が誰かに知られることはありません。） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageWithSymptomsDescription1 {
            get {
                return ResourceManager.GetString("NotifyOtherPageWithSymptomsDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/Covid-19Radar/Covid19Radar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOthersLearnMoreUrl {
            get {
                return ResourceManager.GetString("NotifyOthersLearnMoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   後で陽性の登録をしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PositiveRegistrationConfirmText {
            get {
                return ResourceManager.GetString("PositiveRegistrationConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PositiveRegistrationText {
            get {
                return ResourceManager.GetString("PositiveRegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プライバシーポリシー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrivacyPolicyPageTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReAgreeCheckButton {
            get {
                return ResourceManager.GetString("ReAgreeCheckButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プライバシーポリシーの改定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReAgreePrivacyPolicyPageTitle {
            get {
                return ResourceManager.GetString("ReAgreePrivacyPolicyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プライバシーポリシーを確認する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReAgreePrivacyPolicyTextLink {
            get {
                return ResourceManager.GetString("ReAgreePrivacyPolicyTextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用規約を確認する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReAgreeTermsOfServiceTextLink {
            get {
                return ResourceManager.GetString("ReAgreeTermsOfServiceTextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用規約の改定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReAgreeTermsOfServiceTitle {
            get {
                return ResourceManager.GetString("ReAgreeTermsOfServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveCompleted {
            get {
                return ResourceManager.GetString("SaveCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作情報ID： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendIdMailBody1 {
            get {
                return ResourceManager.GetString("SendIdMailBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \r\n\r\n\r\n※氏名、電話番号など個人情報を記入する必要はありません。\r\n\r\n※動作情報IDは消さずにこのまま送信してください。\r\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendIdMailBody2 {
            get {
                return ResourceManager.GetString("SendIdMailBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COCOA 動作情報IDの送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendIdMailSubject {
            get {
                return ResourceManager.GetString("SendIdMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendingError {
            get {
                return ResourceManager.GetString("SendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールで動作情報IDを送信する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogCompletePageButton1 {
            get {
                return ResourceManager.GetString("SendLogCompletePageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了してホームに戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogCompletePageButton2 {
            get {
                return ResourceManager.GetString("SendLogCompletePageButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作情報を送信しました
        ///続いてメールで動作情報IDを送信してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogCompletePageDescription1 {
            get {
                return ResourceManager.GetString("SendLogCompletePageDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あらかじめメールでお問い合わせいただいた内容と、お送りいただいた動作情報とを紐付けることで、解決策のご案内やCOCOAの改善に活かすことができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogCompletePageDescription2 {
            get {
                return ResourceManager.GetString("SendLogCompletePageDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同意して送信する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogConfirmationPageButton1 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作情報の送信により、COCOAの改善にご協力をお願いします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogConfirmationPageDescription1 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信される情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogConfirmationPageDescription2 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不具合の原因調査に役立つCOCOAの動作情報と利用環境情報（COCOAのバージョン、OS、OSバージョン、端末機種） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogConfirmationPageDescription3 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信されない情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogConfirmationPageDescription4 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号やメールアドレスなどの個人識別可能な情報や位置情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogConfirmationPageDescription5 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ・送信が完了した後に、[メールで動作情報IDを送信する]に進んでいただくことにより、動作情報ID（直前に送信された情報に対して振り出されたIDです）とともに、あなたが感じた不具合の内容をメールでお問い合わせいただくことができます。この場合には、送信された情報をお問い合わせ内容と紐付けてCOCOAの改善に活かします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogConfirmationPageDescription6 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ・送信された情報は、厚生労働省と、厚生労働省からCOCOAの保守運用の委託を受けた事業者のみが取扱い、COCOAの改善のためだけに使用し、不具合情報の調査終了後、速やかに削除します。利用者の同意なしに第三者に提供することはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogConfirmationPageDescription7 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ・[動作情報を確認する]をタップいただくことにより、含まれる情報をご確認いただくことができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogConfirmationPageDescription8 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作情報を確認する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogConfirmationPageTextLink1 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageTextLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作情報の送信について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendLogConfirmationPageTitle {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作情報を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageButton_ShowLogsPage {
            get {
                return ResourceManager.GetString("SettingsPageButton_ShowLogsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次回起動時にチュートリアルを表示/非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageButton_ShowTutorialNextTime {
            get {
                return ResourceManager.GetString("SettingsPageButton_ShowTutorialNextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageButton1 {
            get {
                return ResourceManager.GetString("SettingsPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bluetoothによる接触の検知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageDescription1 {
            get {
                return ResourceManager.GetString("SettingsPageDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性者との接触通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageDescription2 {
            get {
                return ResourceManager.GetString("SettingsPageDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用を中止して過去14日間の接触履歴を消去 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageDescription3 {
            get {
                return ResourceManager.GetString("SettingsPageDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次回起動時にチュートリアルを非表示にします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageDialog_ShowTutorialNextTime_Hide {
            get {
                return ResourceManager.GetString("SettingsPageDialog_ShowTutorialNextTime_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次回起動時にチュートリアルを表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageDialog_ShowTutorialNextTime_Show {
            get {
                return ResourceManager.GetString("SettingsPageDialog_ShowTutorialNextTime_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべての設定とデータが削除されました。アプリケーションを再起動してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageDialogResetCompletedText {
            get {
                return ResourceManager.GetString("SettingsPageDialogResetCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのデータをリセットしますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageDialogResetText {
            get {
                return ResourceManager.GetString("SettingsPageDialogResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのデータを削除する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageDialogResetTitle {
            get {
                return ResourceManager.GetString("SettingsPageDialogResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触の検出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageLabel1 {
            get {
                return ResourceManager.GetString("SettingsPageLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageLabel2 {
            get {
                return ResourceManager.GetString("SettingsPageLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリの使用中止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageLabel3 {
            get {
                return ResourceManager.GetString("SettingsPageLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリの設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.stopcovid19.jp/#ja に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StopCOVID19JPUrl {
            get {
                return ResourceManager.GetString("StopCOVID19JPUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同意して陽性登録する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageButton {
            get {
                return ResourceManager.GetString("SubmitConsentPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性登録の前にお読みください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageDescription1 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理番号が正しい場合には、症状が始まった日または検査を受けた日の2日前以降にあなたと接触した人（概ね1メートル以内で15分以上近接した可能性のあるアプリ使用者）に、通知が届きます。その通知が届いた人に、あなた個人が特定される情報が知られることはありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageDescription10 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ・陽性登録すると、あなたと接触した人に通知が届きます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageDescription2 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ・その通知が届いた人に、あなた個人が特定される情報が知られることはありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageDescription3 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ・感染拡大防止のため、登録にご協力をお願いします に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageDescription4 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳しくは以下をお読みください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageDescription5 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたが保健所や医療機関に伝えた（※）携帯電話番号またはメールアドレスが「新型コロナウイルス感染症等情報把握・管理支援システム」という全国的システム（以下「管理システム」という）に登録されています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageDescription6 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   （※）新型コロナウイルスの検査で陽性となった時などに連絡先として伝えたもの に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageDescription7 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたが保健所にCOCOAへの陽性登録を申し出ると、その携帯電話番号またはメールアドレスに、管理システムから「処理番号」が通知されます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageDescription8 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたが処理番号をCOCOAに入力すると、あなたの携帯電話から管理システムに対し、正しい処理番号であるかどうかの照会が行われます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageDescription9 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性登録への同意 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageTitle1 {
            get {
                return ResourceManager.GetString("SubmitConsentPageTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性登録への同意 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitConsentPageTitle2 {
            get {
                return ResourceManager.GetString("SubmitConsentPageTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSの「設定」→「ストレージ」→「ファイル」、またはファイル管理アプリを利用して以下フォルダをご確認ください。
        ///保存場所： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuccessMessageToSaveOperatingInformationForAndroid {
            get {
                return ResourceManager.GetString("SuccessMessageToSaveOperatingInformationForAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///※「/Android」より前の部分は、お使いの環境によって「内部ストレージ」など表記が異なります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuccessMessageToSaveOperatingInformationForAndroid2 {
            get {
                return ResourceManager.GetString("SuccessMessageToSaveOperatingInformationForAndroid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作情報の確認用ファイルを保存しました。ファイルアプリの「このiPhone内」から確認できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuccessMessageToSaveOperatingInformationForIOS {
            get {
                return ResourceManager.GetString("SuccessMessageToSaveOperatingInformationForIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用規約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TermsofservicePageTitle {
            get {
                return ResourceManager.GetString("TermsofservicePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録は匿名で行われ、氏名や連絡先など個人が特定される情報を登録する必要はありません。また、接触した場所の位置情報が記録や通知されることもありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThankYouNotifyOtherPageDescription1 {
            get {
                return ResourceManager.GetString("ThankYouNotifyOtherPageDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陽性のご登録をいただきありがとうございました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThankYouNotifyOtherPageLabel1 {
            get {
                return ResourceManager.GetString("ThankYouNotifyOtherPageLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleLicenseAgreement {
            get {
                return ResourceManager.GetString("TitleLicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータス設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleUserStatusSettings {
            get {
                return ResourceManager.GetString("TitleUserStatusSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage1Button {
            get {
                return ResourceManager.GetString("TutorialPage1Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本アプリをスマートフォンに設定した人どうしの接触を記録します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage1Description1 {
            get {
                return ResourceManager.GetString("TutorialPage1Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新型コロナウイルスに陽性と判定されたら本アプリに匿名で登録することができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage1Description2 {
            get {
                return ResourceManager.GetString("TutorialPage1Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最近接触した人の中に陽性登録した人がいたら、通知と適切な行動をお知らせします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage1Description3 {
            get {
                return ResourceManager.GetString("TutorialPage1Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリでできること に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage1Title1 {
            get {
                return ResourceManager.GetString("TutorialPage1Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリでできること に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage1Title2 {
            get {
                return ResourceManager.GetString("TutorialPage1Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プライバシーについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage2Description1 {
            get {
                return ResourceManager.GetString("TutorialPage2Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   氏名・電話番号などの個人情報や、GPSなどスマートフォンの位置情報を使うことはなく、記録されることもありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage2Description2 {
            get {
                return ResourceManager.GetString("TutorialPage2Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触の記録は、暗号化され、あなたのスマートフォンの中にのみ記録され、14日後に自動的に削除されます。行政機関や第三者が暗号化された情報を利用して接触歴を把握することはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage2Description3 {
            get {
                return ResourceManager.GetString("TutorialPage2Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触の記録はいつでも止めることができます。アプリ内の設定を無効にするか、アプリを削除してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage2Description4 {
            get {
                return ResourceManager.GetString("TutorialPage2Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用規約へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage2Description5 {
            get {
                return ResourceManager.GetString("TutorialPage2Description5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プライバシーについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage2Title {
            get {
                return ResourceManager.GetString("TutorialPage2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   規約に同意して次へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage3ButtonText {
            get {
                return ResourceManager.GetString("TutorialPage3ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用規約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage3Title {
            get {
                return ResourceManager.GetString("TutorialPage3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage4Button1 {
            get {
                return ResourceManager.GetString("TutorialPage4Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あとで設定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage4Button2 {
            get {
                return ResourceManager.GetString("TutorialPage4Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本アプリで接触検知をご利用いただくために、スマートフォンのBluetooth通信を有効にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage4Description {
            get {
                return ResourceManager.GetString("TutorialPage4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   技術的な詳細について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage4Label {
            get {
                return ResourceManager.GetString("TutorialPage4Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触検知をご利用いただくために に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage4Title1 {
            get {
                return ResourceManager.GetString("TutorialPage4Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接触検知をご利用いただくために に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage4Title2 {
            get {
                return ResourceManager.GetString("TutorialPage4Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知をご利用いただくために に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage5Description1 {
            get {
                return ResourceManager.GetString("TutorialPage5Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本アプリで接触の通知をご利用いただくために、本アプリのプッシュ通知を有効にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage5Description2 {
            get {
                return ResourceManager.GetString("TutorialPage5Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage5Description3 {
            get {
                return ResourceManager.GetString("TutorialPage5Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あとで設定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage5Description4 {
            get {
                return ResourceManager.GetString("TutorialPage5Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知をご利用いただくために に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage5Title {
            get {
                return ResourceManager.GetString("TutorialPage5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム画面へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage6ButtonText1 {
            get {
                return ResourceManager.GetString("TutorialPage6ButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使い方を学ぶ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage6ButtonText2 {
            get {
                return ResourceManager.GetString("TutorialPage6ButtonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご登録いただきありがとうございました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TutorialPage6Label1 {
            get {
                return ResourceManager.GetString("TutorialPage6Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://covid19radarjpnprod.z11.web.core.windows.net/ja/chatbot2.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlContactedForm {
            get {
                return ResourceManager.GetString("UrlContactedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://covid19radar.z11.web.core.windows.net/phone.json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlContactedPhone {
            get {
                return ResourceManager.GetString("UrlContactedPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.mhlw.go.jp/cocoa/privacypolicy_japanese.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlPrivacyPolicy {
            get {
                return ResourceManager.GetString("UrlPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.mhlw.go.jp/cocoa/kiyaku_japanese.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlTermOfUse {
            get {
                return ResourceManager.GetString("UrlTermOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://covid19radarjpnprod.z11.web.core.windows.net/ja/terms_update.json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlTermsUpdate {
            get {
                return ResourceManager.GetString("UrlTermsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://covid19radar.z11.web.core.windows.net/version.json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlVersion {
            get {
                return ResourceManager.GetString("UrlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://ja.wikipedia.org/wiki/%E6%96%B0%E5%9E%8B%E3%82%B3%E3%83%AD%E3%83%8A%E3%82%A6%E3%82%A4%E3%83%AB%E3%82%B9%E6%84%9F%E6%9F%93%E7%97%87%E3%81%AE%E4%B8%96%E7%95%8C%E7%9A%84%E6%B5%81%E8%A1%8C に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WikipediaUrl {
            get {
                return ResourceManager.GetString("WikipediaUrl", resourceCulture);
            }
        }
    }
}
